apiVersion: v1
kind: Service
metadata:
  name: gredfin-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: gredfin-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gredfin-backend
  name: gredfin-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gredfin-backend
  template:
    metadata:
      labels:
        app: gredfin-backend
    spec:
      containers:
      - image: "{{DOCKER_REPO}}{{SERVER_IMG_TAG}}"
        imagePullPolicy: Always
        name: gredfin-backend
        envFrom:
        - secretRef:
            name: gredfin-secret-server-envs
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
