apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gredfin
    component: property-worker
  name: gredfin-property-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gredfin
      component: property-worker
  template:
    metadata:
      labels:
        app: gredfin
        component: property-worker
    spec:
      containers:
      - image: "{{DOCKER_REPO}}{{CLI_IMG_TAG}}"
        imagePullPolicy: Always
        name: gredfin-property-worker
        envFrom:
        - secretRef:
            name: gredfin-secret-worker-envs
        command: ["./cli"]
        args: ["run", "property-worker"]
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
